"""Compile reference map/stat data and local font into freestanding C assets."""
import json, os
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent
def read(name):
    s = (ROOT / 'reference' / (name + '.js')).read_text('utf8')
    return json.loads(s[s.index('{'):].strip().rstrip(';'))

def generate():
    names = ['MT'+str(i) for i in range(23)] + ['MT23w','MT23e','MT23s','MT_1']
    floors = [read('floors_'+n) for n in names]
    maps, enemies = read('maps'), read('enemys')
    out = ['/* Generated by generate.py. See SOURCES.md. */', '#define FLOORS 27',
           'static const unsigned short initial_maps[FLOORS][121] = {']
    for f in floors:
        cells = [v for row in f['map'][1:12] for v in row[1:12]]
        assert len(cells)==121
        out.append('{'+','.join(map(str,cells))+'},')
    out += ['};','typedef struct { int floor,x,y,to,tx,ty; } Stair;', 'static const Stair stairs[] = {']
    for i,f in enumerate(floors):
        for loc,v in f['changeFloor'].items():
            x,y = map(int,loc.split(',')); dest=v['floorId']
            j = i+1 if dest==':next' else i-1 if dest==':before' else names.index(dest)
            # East and south wings must return to the corresponding stair.
            pos = floors[j].get(v.get('stair','downFloor'), [6,8])
            if i==23 and j==22: pos=[1,6]
            if i==24 and j==22: pos=[11,6]
            if i==25 and j==22: pos=[6,11]
            out.append('{'+','.join(map(str,[i,x-1,y-1,j,pos[0]-1,pos[1]-1]))+'},')
    out += ['};','typedef struct { int hp,atk,def,gold,exp,special,extra; const char *name; } Enemy;',
            'static const Enemy enemy_base[300] = {']
    for key,mp in maps.items():
        i=int(key)
        if i>=300 or mp['id'] not in enemies: continue
        e=enemies[mp['id']]
        special=e.get('special',0)
        if isinstance(special,list): special=special[0] if special else 0
        out.append('[%d]={%d,%d,%d,%d,%d,%d,%d,%s},'%(i,e['hp'],e['atk'],e['def'],e['money'],e['exp'],special,e.get('damage',0),json.dumps(e['name'],ensure_ascii=False)))
    out += ['};']
    (ROOT/'data.h').write_text('\n'.join(out),encoding='utf8')
    # Rasterize only glyphs used in our source. No firmware font dependency.
    source=(ROOT/'story.h').read_text('utf8')+''.join(p.read_text('utf8') for p in ROOT.glob('*.c'))+'\n'.join(out)
    chars=sorted(set(chr(i) for i in range(32,127)) | {c for c in source if ord(c)>127})
    font=ImageFont.truetype(os.environ.get('MOTA_FONT', str(Path(os.environ.get('WINDIR', 'C:/Windows'))/'Fonts/simsun.ttc')),12)
    out=['typedef struct { unsigned int code; unsigned short rows[12]; } Glyph;', 'static const Glyph glyphs[] = {']
    for c in chars:
        im=Image.new('1',(12,12));d=ImageDraw.Draw(im)
        # Shared font origin, NOT each glyph's bounding-box top: digits and
        # punctuation must retain their position relative to Chinese baselines.
        left,top,right,bottom=font.getbbox(c)
        d.text((0,-1),c,font=font,fill=1)
        rows=[sum((1<<(11-x)) for x in range(12) if im.getpixel((x,y))) for y in range(12)]
        out.append('{%d,{%s}},'%(ord(c),','.join(map(str,rows))))
    out+=['};']
    (ROOT/'font.h').write_text('\n'.join(out),encoding='utf8')
    generate_sprites(maps, floors)
    print('Generated 27 areas,',len(chars),'glyphs')

def generate_sprites(maps, floors):
    assets=ROOT/'assets'
    s=(assets/'icons.js').read_text('utf8')
    icons=json.loads(s[s.index('{'):].strip().rstrip(';'))
    sheets={c:Image.open(assets/(c+'.png')).convert('RGBA') for c in ['terrains','animates','enemys','items','npcs']}
    hero=Image.open(assets/'brave.png').convert('RGBA')
    ground=Image.open(assets/'ground.png').convert('RGBA')
    used=sorted({v for f in floors for row in f['map'] for v in row}|{258,300,301,302,303})
    tiles=[]
    index=[0]*304
    for t in used:
        index[t]=len(tiles)//2
        for frame in range(2):
            base=Image.new('RGBA',(32,32),(32,32,32,255));base.alpha_composite(ground)
            if t>=300:
                row=t-300
                sprite=hero.crop((frame*32,row*32,frame*32+32,row*32+32))
                base.alpha_composite(sprite)
            elif t:
                m=maps[str(t)];cls=m['cls'];row=icons[cls][m['id']]
                # The animates sheet also contains STATIC walls and door-opening
                # sequences. Cycling these columns erases walls / opens doors.
                animated=cls in ['enemys','npcs'] or m['id'] in ['star','lava']
                col=frame if animated else 0
                sheet=sheets[cls]
                col=min(col,sheet.width//32-1)
                base.alpha_composite(sheet.crop((col*32,row*32,col*32+32,row*32+32)))
            tiles.append(base.convert('RGB').resize((20,20),Image.Resampling.NEAREST))
    # Store exact 565 pixels: no image decoder or external files on the device.
    out=['/* Classic sprites, converted to 20x20 RGB565. See SOURCES.md. */',
         'static const unsigned short sprite_index[304] = {'+','.join(map(str,index))+'};',
         'static const unsigned short sprite_pixels[%d][400] = {'%len(tiles)]
    for im in tiles:
        values=[max(1,((r&248)<<8)|((g&252)<<3)|(b>>3)) for r,g,b in im.getdata()]
        out.append('{'+','.join(map(str,values))+'},')
    out+=['};']
    out.append('static const unsigned short hero_pixels[4][4][400] = {')
    for direction in range(4):
        out.append('{')
        for frame in range(4):
            base=Image.new('RGBA',(32,32),(32,32,32,255));base.alpha_composite(ground)
            base.alpha_composite(hero.crop((frame*32,direction*32,frame*32+32,direction*32+32)))
            im=base.convert('RGB').resize((20,20),Image.Resampling.NEAREST)
            values=[max(1,((r&248)<<8)|((g&252)<<3)|(b>>3)) for r,g,b in im.getdata()]
            out.append('{'+','.join(map(str,values))+'},')
        out.append('},')
    out.append('};')
    out.append('static const unsigned short key_icons[3][196] = {')
    for name in ['yellowKey','blueKey','redKey']:
        row=icons['items'][name]
        im=sheets['items'].crop((0,row*32,32,row*32+32)).resize((14,14),Image.Resampling.NEAREST)
        values=[0 if a<128 else max(1,((r&248)<<8)|((g&252)<<3)|(b>>3)) for r,g,b,a in im.getdata()]
        out.append('{'+','.join(map(str,values))+'},')
    out.append('};')
    (ROOT/'sprites.h').write_text('\n'.join(out),encoding='utf8')
    preview=Image.new('RGB',(20*12,40*((len(used)+11)//12)),(32,32,32))
    for i in range(len(used)):
        preview.paste(tiles[i*2],((i%12)*20,(i//12)*40))
        ImageDraw.Draw(preview).text(((i%12)*20,(i//12)*40+21),str(used[i]),fill='white')
    preview.save(assets/'atlas-preview.png')

if __name__=='__main__': generate()
